	
service: arthouse-server
 
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'staging'}
  region: us-east-1
  environment:
    ENVIRONMENT_NAME: ${self:provider.stage}
    CONTRACT_DEPLOYMENT_WALLET_PRIVATE_KEY: ""
    INFURA_API_KEY: ""
    ATILA_USER_PROFILE_API_KEY: ""

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  saveNFTAPI:
    handler: handler.handler
    tracing: Active
    description: "Create an NFT"
    events:
      - http:
          path: api/v1/nft
          method: post
          cors: true
          integration: lambda-proxy
    timeout: 300 # 300 seconds = 5 minutes
  index:
    description: "Landing page endpoint to show information about the API."
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
          integration: lambda-proxy
    timeout: 10